config/routes.rb
Recruiting::Application.routes.draw do
  
  resources :developer_profiles

  match "/", to: "home#index", via: [:get]
  match "/investments", to: "home#investments", :as => :investments, via: [:get]
  match "/developers", to: "home#developers", :as => :developers, via: [:get]
  match "/developers/next-steps", to: "home#next_steps", :as => :developers_next_steps, via: [:get]
  match '/accept_legal_message.js', to: 'deals#accept_legal_popup', :as => :accept_legal_popup, :via => [:get]

  match 'deals/show_photo', to: 'deals#show_photo', :via => [:get]
  match 'follow/follow_deal', to: 'follow#follow_deal', :via => [:get]

  resources(:deals) do
    match '/publish', to: 'deals#publish', :as => :publish, :via => [:post, :put]
    match '/unpublish', to: 'deals#unpublish', :as => :unpublish, :via => [:post, :put]
  end

  devise_scope :user do
    match '/logout', to: 'auth/sessions#destroy', :as => :logout, :via => [:get, :post]
  end
  devise_for :users, :controllers => { :registrations => "auth/registrations" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: "home#index"

end

app/models/developer_profile.rb
class DeveloperProfile < ActiveRecord::Base
  belongs_to :user
  
  TYPICAL_PROJECT_SIZE = ["$50-250K", "$250-500K", "$500k-$1M", "$1-5M", "$5-10M", "$10-50M", ">$50M"]
  EXPERIENCE = ["0-5 years", "5-10", "10-20", ">20"]
  EMPLOYMENT = ["Part Time", "Full Time"]
  PROJECTS_PER_YEAR = ["0-5", "5-10", "10-20", "20+"]
  WHERE_DID_YOU_HEAR =  ["Web Search", "Facebook", "LinkedIn", "Twitter", "News Article", "Online Discussion Board", "Trade Association", "Friend / Associate"]
  
  before_update :check_for_completed_profile
  
  # validates :employment, presence: true, :on => :update
  # validates :experience, presence: true, :on => :update
  # validates :yearly_projects, presence: true, :on => :update
  # validates :typical_project_size, presence: true, :on => :update
  validates :employment, presence: true
  validates :experience, presence: true
  validates :yearly_projects, presence: true
  validates :typical_project_size, presence: true
  
  state_machine :state, :initial => :started do
    event :complete do
      transition any => :completed
    end    
  end

  def completed_profile?
    (employment && experience && yearly_projects && typical_project_size)
  end

  def check_for_completed_profile
    self.complete if completed_profile? && !self.completed?
  end
end

app/controllers/developer_profiles_controller.rb
class DeveloperProfilesController < InheritedResources::Base
  
  def next_steps
    
  end
end

app/views/developer_profiles/_form.html.erb
<%= form_for(@developer_profile) do |f| %>
  <% if @developer_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@developer_profile.errors.count, "error") %> prohibited this developer_profile from being saved:</h2>

      <ul>
      <% @developer_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :employment %><br>
    <%= f.text_field :employment %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_field :experience %>
  </div>
  <div class="field">
    <%= f.label :yearly_projects %><br>
    <%= f.text_field :yearly_projects %>
  </div>
  <div class="field">
    <%= f.label :typical_project_size %><br>
    <%= f.text_field :typical_project_size %>
  </div>
  <div class="field">
    <%= f.label :how_did_you_hear %><br>
    <%= f.text_field :how_did_you_hear %>
  </div>
  <div class="field">
    <%= f.label :how_response %><br>
    <%= f.text_field :how_response %>
  </div>
  <div class="field">
    <%= f.label :why %><br>
    <%= f.text_field :why %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/developer_profiles/edit.html.erb
<h1>Editing developer_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @developer_profile %> |
<%= link_to 'Back', developer_profiles_path %>

app/views/developer_profiles/index.html.erb
<h1>Listing developer_profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Employment</th>
      <th>Experience</th>
      <th>Yearly projects</th>
      <th>Typical project size</th>
      <th>How did you hear</th>
      <th>How response</th>
      <th>Why</th>
      <th>State</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @developer_profiles.each do |developer_profile| %>
      <tr>
        <td><%= developer_profile.user_id %></td>
        <td><%= developer_profile.employment %></td>
        <td><%= developer_profile.experience %></td>
        <td><%= developer_profile.yearly_projects %></td>
        <td><%= developer_profile.typical_project_size %></td>
        <td><%= developer_profile.how_did_you_hear %></td>
        <td><%= developer_profile.how_response %></td>
        <td><%= developer_profile.why %></td>
        <td><%= developer_profile.state %></td>
        <td><%= link_to 'Show', developer_profile %></td>
        <td><%= link_to 'Edit', edit_developer_profile_path(developer_profile) %></td>
        <td><%= link_to 'Destroy', developer_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Developer profile', new_developer_profile_path %>

app/views/developer_profiles/new.html.erb
<h1>New developer_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', developer_profiles_path %>

app/views/developer_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @developer_profile.user_id %>
</p>

<p>
  <strong>Employment:</strong>
  <%= @developer_profile.employment %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @developer_profile.experience %>
</p>

<p>
  <strong>Yearly projects:</strong>
  <%= @developer_profile.yearly_projects %>
</p>

<p>
  <strong>Typical project size:</strong>
  <%= @developer_profile.typical_project_size %>
</p>

<p>
  <strong>How did you hear:</strong>
  <%= @developer_profile.how_did_you_hear %>
</p>

<p>
  <strong>How response:</strong>
  <%= @developer_profile.how_response %>
</p>

<p>
  <strong>Why:</strong>
  <%= @developer_profile.why %>
</p>

<p>
  <strong>State:</strong>
  <%= @developer_profile.state %>
</p>

<%= link_to 'Edit', edit_developer_profile_path(@developer_profile) %> |
<%= link_to 'Back', developer_profiles_path %>