config/routes.rb
Recruiting::Application.routes.draw do
  
  resources :developer_profiles

  match "/", to: "home#index", via: [:get]
  match "/investments", to: "home#investments", :as => :investments, via: [:get]
  match "/developers", to: "home#developers", :as => :developers, via: [:get]
  match "/developers/next-steps", to: "home#next_steps", :as => :developers_next_steps, via: [:get]
  match '/accept_legal_message.js', to: 'deals#accept_legal_popup', :as => :accept_legal_popup, :via => [:get]

  match 'deals/show_photo', to: 'deals#show_photo', :via => [:get]
  match 'follow/follow_deal', to: 'follow#follow_deal', :via => [:get]

  resources(:deals) do
    match '/publish', to: 'deals#publish', :as => :publish, :via => [:post, :put]
    match '/unpublish', to: 'deals#unpublish', :as => :unpublish, :via => [:post, :put]
  end

  devise_scope :user do
    match '/logout', to: 'auth/sessions#destroy', :as => :logout, :via => [:get, :post]
  end
  devise_for :users, :controllers => { :registrations => "auth/registrations" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: "home#index"

end

app/views/shared/headers/_account.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container-fluid
    <!-- Brand and toggle get grouped for better mobile display -->
    .navbar-header
      %button.navbar-toggle{type: "button", "data-toggle"=>"collapse", "data-target"=>"#bs-example-navbar-collapse-1"}
        %span.sr-only="Toggle navigation"
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to(image_tag("logos/logo.png"), root_path, class: "navbar-brand")

    <!-- Collect the nav links, forms, and other content for toggling -->
    .collapse.navbar-collapse{ id: "bs-example-navbar-collapse-1"}
      %ul.nav.navbar-nav.navbar-right
        %li{class: ((content_for :header_tab) == "instructions" ? "active" : "")}
          = link_to("Instructions", root_path)
        %li{class: ((content_for :header_tab) == "investments" ? "active" : "")}
          = link_to("Investments", investments_path)
        %li{class: ((content_for :header_tab) == "deals" ? "active" : "")}
          = link_to("Projects", deals_path)
        %li{class: ((content_for :header_tab) == "account" ? "active" : "")}
          = link_to("Logout", destroy_user_session_path, :method => :delete)

app/views/shared/headers/_website.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container-fluid
    <!-- Brand and toggle get grouped for better mobile display -->
    .navbar-header
      %button.navbar-toggle{type: "button", "data-toggle"=>"collapse", "data-target"=>"#bs-example-navbar-collapse-1"}
        %span.sr-only="Toggle navigation"
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to(image_tag("logos/logo.png"), root_path, class: "navbar-brand")
      

    <!-- Collect the nav links, forms, and other content for toggling -->
    .collapse.navbar-collapse{ id: "bs-example-navbar-collapse-1"}
      %ul.nav.navbar-nav.navbar-right
        %li{class: ((content_for :header_tab) == "instructions" ? "active" : "")}
          = link_to("Instructions", root_path)
        %li{class: ((content_for :header_tab) == "investments" ? "active" : "")}
          = link_to("Investments", investments_path)
        %li{class: ((content_for :header_tab) == "developers" ? "active" : "")}
          = link_to("Developers", developers_path)
        %li{class: ((content_for :header_tab) == "account" ? "active" : "")}
          = link_to("Login", new_user_session_path)