config/routes.rb
Recruiting::Application.routes.draw do
  
  resources :developer_profiles

  match "/", to: "home#index", via: [:get]
  match "/investments", to: "home#investments", :as => :investments, via: [:get]
  match "/developers", to: "home#developers", :as => :developers, via: [:get]
  match "/developers/next-steps", to: "home#next_steps", :as => :developers_next_steps, via: [:get]
  match '/accept_legal_message.js', to: 'deals#accept_legal_popup', :as => :accept_legal_popup, :via => [:get]

  match 'deals/show_photo', to: 'deals#show_photo', :via => [:get]
  match 'follow/follow_deal', to: 'follow#follow_deal', :via => [:get]

  resources(:deals) do
    match '/publish', to: 'deals#publish', :as => :publish, :via => [:post, :put]
    match '/unpublish', to: 'deals#unpublish', :as => :unpublish, :via => [:post, :put]
  end

  devise_scope :user do
    match '/logout', to: 'auth/sessions#destroy', :as => :logout, :via => [:get, :post]
  end
  devise_for :users, :controllers => { :registrations => "auth/registrations" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: "home#index"

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  include Groundfloor::Addressable
  
  belongs_to :user
  
  scope :published, -> {    
    self.with_state(:published)
  }
  
  monetize :amount_to_raise_cents
  
  CLOSE_TIMELINE = ['Oct 2014', 'Nov 2014', 'Dec 2014', '2015', "Flexible"]
  CAPITAL_TYPE =  ["Debt",  "Equity", "Both", "Flexible"]
  
  # RULES
  INVALID_DATES=['Jun 2014', 'Jul 2014', 'Aug 2014', 'Sept 2014', '']
  INVALID_CAPITAL_TYPES=['Equity','Both','']
  
  before_save :validate_project
  
  state_machine :state, :initial => :new do
    
    event :upgrade do
      transition :new => :unpublished, :unpublished => :published, :published => :closed
    end    

    event :downgrade do
      transition :closed => :published, :published => :unpublished, :unpublished => :new
    end    
    
    event :pass_submission do
      transition any => :published
    end    

    event :fail_submission do
      transition any => :failed_submission
    end    

    event :publish do
      transition any => :published
    end    

    event :unpublish do
      transition any => :unpublished
    end
    
    state all - [:failed_submission, :new] do
      def acceptable?
        true
      end
    end

    state :failed_submission, :new do
      def acceptable?
        false
      end
    end
    
    state all - [:new, :unpublished] do
      def is_pending_approval?
        false
      end
    end
    
    state :new, :unpublished do
      def is_pending_approval?
        true
      end
    end
  
    state all - [:unpublished, :failed_submission, :new, :closed] do
      def is_published?
        true
      end
    end
    
    state :unpublished, :failed_submission, :new, :closed do
      def is_published?
        false
      end
    end
  end
  
  def state_name
    case self.state.to_s
    when "pending_submission"
      "Pending Approval"
    when "pending_approval"
      "Pending Approval"
    else
      self.state.split("_").join(" ")
    end
  end
  
  # Nested Attributes Objects.. Automatically build if there is nothing there
  def address
    super || build_address
  end

  def invalid_deal?
    ( INVALID_DATES.include?(self.close_timeline) ||
      self.amount_to_raise > 200000 ||
      INVALID_CAPITAL_TYPES.include?(self.capital_type) ||
      self.address.state != 'GA'
    )
  end
  
  def validate_project
    if invalid_deal?
      self.state = "failed_submission"
    else
      self.state = "published" unless self.closed?
    end
  end

  def has_photo
    if Photo.where(:deal_id => self.id).size > 0
      true
    else
      false
    end
  end
end

app/controllers/deals_controller.rb
class DealsController < InheritedResources::Base
  before_filter :authenticate_user!, :except => [:index]

  def import_photo
    if @photo_param
      photos = Photo.where(:deal_id => @deal.id)
      if photos
        photos.destroy_all
      end
      @photo = Photo.new
      @photo.image_file = @photo_param
      @photo.deal_id = @deal.id
      @photo.save
    end
  end
  
  def extract_photo
    if params[:deal][:image_file]
      params[:deal].each do |k, v|
        if k == 'image_file'
          @photo_param = params[:deal][:image_file]
          params[:deal].delete(k)
        end
      end
    end
  end

  def index
    @deals = current_user.deals.order(:name)
    return redirect_to "/developers/next-steps" if @deals.length < 1
  end

  def create
    extract_photo

    @deal = Deal.new(permitted_params.merge({ user_id: current_user.id }))
    create! do |success, failure|
      success.html {
        # This is *not* the ideal place to put this,
        # but it will work for now.
        import_photo
        flash.now[:success] = "Your proposal was created."
        redirect_to deals_path
      }
      failure.html {
        flash.now[:error] = "Your project was not created. Please address the errors listed below and try again: <br><span>#{@deal.errors.full_messages.join('<br>')}</span>"
        render :new
      }
    end
  end

  def new
    @deal = Deal.new
  end

  def update
    extract_photo

    @deal = current_user.deals.where(:id => params[:id]).first || Deal.new(permitted_params.merge({user_id: current_user.id }))

    @deal.assign_attributes(permitted_params)
    @deal.validate_project
    if @deal.save
      # This is *not* the ideal place to put this,
      # but it will work for now.
      import_photo
      flash[:success] = "Your proposal was updated."
      redirect_to deals_path
    else
      flash.now[:error] = "Your project was not updated. Please address the errors listed below and try again: <br><span>#{@deal.errors.full_messages.join('<br>')}</span>"
      render :edit
    end
  end

  def destroy
    destroy!(:info => "Your project was removed.") do |format|
      @deals = current_user.deals.order(:name)

      if @deals.length < 1
        format.html { redirect_to "/developers/next-steps" }
      else
        format.html { redirect_to deals_path }
      end
    end

  end

  def publish
    flash[:notice]="Great News!  Your deal has been published to our website."
    @deal = current_user.deals.find(params[:deal_id])
    @deal.publish
    redirect_to deal_path(@deal)
  end

  def unpublish
    @deal = current_user.deals.find(params[:deal_id])
    @deal.unpublish
    flash[:notice] = "Your deal has successfully been unpublished and will no longer appear on the public website"
    redirect_to deals_path
  end

  def show_photo
    @image_data = Photo.where(:deal_id => params[:id]).first
    @image = @image_data.binary_data
    send_data(@image, :type => @image_data.content_type, :filename => @image_data.filename, :disposition => 'inline')
  end

  protected
    def permitted_params
      params.require(:deal).permit!
    end

  private :permitted_params

end

app/views/deals/_form.html.haml
= form_for deal, :html => { id: "deal_form", class: "form-horizontal form #{(local_assigns[:additional_class].present? ? additional_class : "")}", role: "form", multipart: true } do |f|
  .col-lg-6
    .row
      %h4="PROPERTY INFORMATION"
      .form-group
        %label.control-label.col-lg-4{"data-original-title" => "Proposal Title", "data-content" => "A descriptive name for this project that will attract investors", "data-placement" => "top", "data-trigger" => "hover", rel: "popover"}
          Project Title
          %i.icon-question-sign
        .col-lg-7
          = f.text_field :name, class: "form-control required", placeholder: "315 West Street Renovation", maxlength: 50, "data-counter" => "name_counter", "data-counter-max" => 50
          %em
            %span{id:'name_counter'}
              #{(50 - (deal.name.present? ? deal.name.length : 0))} 
            characters remaining
          
      = f.fields_for :address do |ff|
        .form-group
          %label.control-label.col-lg-4="City"
          .col-lg-7
            = ff.text_field :city, class: "form-control required"
        .form-group
          %label.control-label.col-lg-4="State"
          .col-lg-7
            = ff.select :state, Address::STATES, { include_blank: "Please select a state" }, { class: "form-control required" }
        .form-group
          %label.control-label.col-lg-4="Zipcode"
          .col-lg-7
            = ff.text_field :zipcode, class: "form-control required"

      .form-group
        %label.control-label.col-lg-4{"data-original-title" => "Project Summary", "data-content" => "This is a descriptive and concise summary of the property that you will use to attract investors.", "data-placement" => "top", "data-trigger" => "hover", rel: "popover"}
          Project Summary
          %i.icon-question-sign
        .col-lg-7
          = f.text_area :short_description, rows: 4, maxlength: 220, class: "form-control required", "data-counter" => "short_description_counter", "data-counter-max" => 220, placeholder: "Refurbished quadraplex with historic charm and significant rental potential. Asset was purchased in foreclosure. All units have rental commitments pending renovation completion."
          %em
            %span{id:'short_description_counter'}
              #{(220 - (deal.short_description.present? ? deal.short_description.length : 0))} 
            characters remaining
          
  .col-lg-6
    .row
      %h4="FINANCIAL INFORMATION"
      .form-group
        %label.control-label.col-lg-4="Amount To Raise"
        .col-lg-4
          .input-group
            %span.input-group-addon="$"
            = f.number_field :amount_to_raise, class: "form-control required", onkeypress: "onlyAllowDigits(event);", step: 1000, value: deal.amount_to_raise.dollars.to_i
            %span.input-group-addon=".00"
            
      .form-group
        %label.control-label.col-lg-4="Capital Type"
        .col-lg-6
          = f.select :capital_type, Deal::CAPITAL_TYPE, { include_blank: "Please select capital type" }, { class: "form-control required" }
      .form-group
        %label.control-label.col-lg-4="Targeted Close"
        .col-lg-6
          = f.select :close_timeline, Deal::CLOSE_TIMELINE, { include_blank: "Please select closing timeframe" }, { class: "form-control required" }
      .form-group
        %label.control-label.col-lg-4="Photo"
        .col-lg-6
          = f.file_field :image_file
          
          

  .row
    .col-lg-12.text-center
      %button.btn.btn-primary.btn-lg{ type: "submit", "data-disable-with" => "SUBMITTING PROJECT" }
        SAVE PROJECT  <i class="icon-chevron-sign-right"></i></button>

app/views/deals/accept_legal_popup.js.erb
$("#legal-popup-following").modal('hide');
$("#legal-popup-investing").modal('hide');

app/views/deals/edit.html.haml
= set_header_state("deals")

.errors
  = display_flash_messages(flash)

%section.container-wrapper
  .container.sign-up
    .row
      .lg-col-12
        %h1="UPDATE YOUR PROJECT"
        %p
          Complete the form below to update your transaction. This information is confidential and will only be used to evaluate your proposal according to our current funding criteria. You can always change or update transaction information later.
          %a{onclick: "gotoAnchor('#how');"}="How we select transactions for funding."
    
    .row.form
      = render "form", deal: @deal
      
%section.container-wrapper.odd.last_call{id: "how"}
  .container
    %h1="HOW WE SELECT TRANSACTIONS FOR FUNDING"
    %p
      It’s the early days of establishing a new kind of finance for real estate transactions. As a new concept, we can’t take on every type and size of deal just yet. Our first cohort is planned for introduction early this year. Successful U.S. investment opportunities will receive funding if they:
    .row.story-board
      .col-lg-4.step
        .icon
          = image_tag("icons/dev_icon_cash.png")
        %p="Require less than $500 thousand of debt financing"
      .col-lg-4.step
        .icon
          = image_tag("icons/dev_icon_usa.png")
        %p="Gain followers"
      .col-lg-4.step
        .icon
          = image_tag("icons/dev_icon_2013cal.png")
        %p="Submit an application"
    %p
      Have a proposal that fits? Great! Provide us with the basic details of your project and start gaining followers immediately. Once you gain enough followers we’ll invite you to apply for financing. The amount of followers you need is determined by the size of your project--we’ll provide you with the tools to leverage your existing network in addition to ours! Even if your proposal doesn’t fit today, it might in the near future. We’re planning to expand in early 2014. If your timeline to close funds is flexible, go ahead and propose your project now -- and we’ll let you know when it’s time to apply.

app/views/deals/follow.js.erb
$("#d<%= @deal.id %> .follower-count").html("<%= @deal.followers_count %>");
$("#d<%= @deal.id %> .action-link.follow").html("<%= escape_javascript(remote_followers_url(@deal)) %>");

app/views/deals/index.html.haml
- set_header_tab("deals")

.errors
  = display_flash_messages(flash)

%section.container-wrapper.odd.last
  .container.dashboard
    .row.headline
      .col-lg-9
        %h1="YOUR PROJECTS"
      .col-lg-3
        = link_to("ADD A PROJECT", new_deal_path, class: "btn btn-primary btn-lg")
  
    %br
    - @deals.in_groups_of(2) do |grouped_deals|
      .row
        - grouped_deals.each do |deal|
          - if deal.present?
            .col-lg-6
              .deal
                %header
                  %span.icon
                    %i.fa.fa-building.fa-2x
                  .title
                    #{(truncate(deal.name.present? ? deal.name : (local_assigns[:show_defaults].present? ? "Property Name" : ""), length: 40))}
                .card
                  .row
                    .col-lg-4
                      - if deal.has_photo
                        = image_tag url_for(:controller => 'deals', :action => 'show_photo', :id => deal.id)
                      - else
                        .placeholder-cover-asset
                          %span
                            No Photo
                            %br
                            Available
                            %br
                    
                    .col-lg-8
                      .row
                        .col-lg-6
                          %label.address
                            #{(deal.address.present? ? deal.address.city : (local_assigns[:show_defaults].present? ? "City" : ""))}, 
                            #{(deal.address.present? ? deal.address.state : (local_assigns[:show_defaults].present? ? "State" : ""))}
                        .col-lg-6
                          .status
                            %label="Status:"
                            - if deal.state.present?
                              - if deal.acceptable?
                                - if deal.unpublished?
                                  %span.good="Qualified"
                                - else
                                  %span.good="#{deal.state_name.titleize}"
                              - else
                                %span.bad="On File"
                            - else 
                              %span
                                #{(local_assigns[:show_defaults].present? ? "N/A" : "")}
                      
                      .row
                        .col-lg-12
                          %p
                            #{deal.short_description}
                          %ul.actions
                            - if deal.acceptable?  && (! deal.is_pending_approval?)
                              - if deal.is_published?
                                %li
                                  =link_to("Unpublish", deal_unpublish_path(deal), :method => :post)
                              - else 
                                %li
                                  =link_to("Publish", deal_publish_path(deal), :method => :post)
                
                            %li
                              =link_to("Edit", edit_deal_path(deal))
                            %li
                              =link_to("Delete", deal_path(deal), :method => :DELETE, :confirm => "Are you sure you want to remove this project?")
              
                .card-footer
                  .row
                    .col-lg-6.amount_to_raise.border
                      #{(deal.amount_to_raise.present? ? number_to_currency(deal.amount_to_raise.dollars, precision: 0) : (local_assigns[:show_defaults].present? ? "N/A" : ""))}
                      %label="amount"
                    .col-lg-6.close-timeline
                      #{(deal.close_timeline.present? ? deal.close_timeline : (local_assigns[:show_defaults].present? ? "N/A" : ""))}
                      %label="close"

    - if @deals.length > 4
      .row
        .col-lg-12.text-center
          =link_to("ADD A PROJECT", new_deal_path, class:"btn btn-primary btn-large")

app/views/deals/new.html.haml
= set_header_state("deals")

.errors
  = display_flash_messages(flash)

%section.container-wrapper
  .container.deal
    .row
      %h1="PROPOSE A NEW TRANSACTION"
      %p
        Complete the form below to propose an additional transaction. This information is confidential and will only be used to evaluate your proposal according to our current funding criteria. You can always change or update transaction information later.
        %a{onclick: "gotoAnchor('#how');"}="How we select transactions for funding."
    
    .row.form
      = render "form", deal: @deal
            
%section.container-wrapper.odd.last_call{id: "how"}
  .container
    %h1="HOW WE SELECT TRANSACTIONS FOR FUNDING"
    %p
      It’s the early days of establishing a new kind of finance for real estate transactions. As a new concept, we can’t take on every type and size of deal just yet. Our first cohort is planned for introduction early this year. Successful U.S. investment opportunities will receive funding if they:
    .row.story-board
      .col-lg-4.step
        .icon
          = image_tag("icons/dev_icon_cash.png")
        %p="Require less than $500 thousand of debt financing"
      .col-lg-4.step
        .icon
          = image_tag("icons/dev_icon_usa.png")
        %p="Gain followers"
      .col-lg-4.step
        .icon
          = image_tag("icons/dev_icon_2013cal.png")
        %p="Submit an application"
    %p
      Have a proposal that fits? Great! Provide us with the basic details of your project and start gaining followers immediately. Once you gain enough followers we’ll invite you to apply for financing. The amount of followers you need is determined by the size of your project--we’ll provide you with the tools to leverage your existing network in addition to ours! Even if your proposal doesn’t fit today, it might in the near future. We’re planning to expand in early 2014. If your timeline to close funds is flexible, go ahead and propose your project now -- and we’ll let you know when it’s time to apply.